name: build

on:
  push:
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true

      # ref_name for tags, sha for commits
      - name: Rename pdf file (for tags)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: mv src/main.pdf 10195101428_刘议临_${{ github.ref_name }}.pdf
      - name: Rename pdf file (for commits)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: mv src/main.pdf 10195101428_刘议临_${{ github.sha }}.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: "*.pdf"

  release:
    needs: [ build-pdf ]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pdf
      # Non-ASCII characters in file names are not supported in GitHub releases
      - run: mv 10195101428_刘议临_${{ github.ref_name }}.pdf 10195101428_${{ github.ref_name }}.pdf
      - uses: softprops/action-gh-release@v1
        with:
          files: 10195101428_${{ github.ref_name }}.pdf
