name: build

on:
  push:
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f

      # ref_name for tags, sha for commits
      - run: mv src/main.pdf ${{ github.ref_name }}.pdf
        if: startsWith(github.ref, 'refs/tags/v')
      - run: mv src/main.pdf ${{ github.sha }}.pdf
        if: !startsWith(github.ref, 'refs/tags/v')

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: "*.pdf"

  release:
    needs: [ build-pdf ]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pdf
      - uses: softprops/action-gh-release@v1
        with:
          files: "*"
