name: build

on:
  push:
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download fonts
        run: |
          wget https://github.com/dolbydu/font/raw/master/unicode/SimSun.ttc
          wget https://github.com/dolbydu/font/raw/master/unicode/FangSong.ttf
      - uses: xu-cheng/latex-action@v2
        continue-on-error: true
        with:
          working_directory: src
          root_file: main.tex
          args: "-pdf -file-line-error -interaction=nonstopmode -xelatex -f"
          extra_fonts: |
            ../SimSun.ttc
            ../FangSong.ttf

      # ref_name for tags, sha for commits
      - name: Rename pdf file (for tags)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: mv src/main.pdf 10195101428_刘议临_${{ github.ref_name }}.pdf
      - name: Rename pdf file (for commits)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: mv src/main.pdf 10195101428_刘议临_${{ github.sha }}.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: "*.pdf"

  release:
    needs: [ build-pdf ]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pdf
      - uses: softprops/action-gh-release@v1
        with:
          files: "*"
